version: '2'
services:
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:latest
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      # Set to true to enable the MQTT transcription plugin
      - MQTT_PLUGIN_ENABLE=true
      - MQTT_BROKER_ADDRESS=

      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=finest

  media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Creds for Bluemix STT
      - WATSON_STT_USERNAME=
      - WATSON_STT_PASSWORD=
      - WATSON_STT_URL=

